breaking change: replaces unlawful instances with similar named funct…
d86leader/purescript-undefined-or pull request #7
Opened 2022-08-17 11:20 UTC by CarstenKoenig

Hi,

this implements the changes proposed in #4 - it removes the unlawful instances and replaces them with just the instance-functions.

Added benefit: can drop dependency on `control` ;)

2022-08-17 12:22 UTC, d86leader requested changes
Looks good with only some problems in comments

2022-08-17 12:22 UTC, d86leader commented on src/Data/UndefinedOr.purs
> +-- | unlawful version of `map` - caution does not obey the functor laws
Nitpick: can you capitalize the comments and fix the punctuation? By fixing I mean `s/ - caution/. Caution:/`

2022-08-17 12:22 UTC, d86leader commented on src/Data/UndefinedOr.purs
> +-- | Please also note that this (althoug it seems like a instance of) is not Functor
Style remark: remove brackets and change the sentence: `s/that this (.*) is not Functor/that this is not a Functor, \1 it/`
Also typo in 'although'

2022-08-17 12:23 UTC, d86leader commented
Oh and another thing: please bump the major version as this is a breaking change.

2022-08-17 13:39 UTC, CarstenKoenig commented
Hi - I'll have a look once I get home - should be no problem

2022-08-17 13:48 UTC, CarstenKoenig commented
Hi - I pushed the changes please have a look.

For the version you have to help me out a bit: I was under the impression that normally you'll use `pulp` (or I think `spago` can do as well) to bump up the version when you release the package - AFAIK that includes adding a Tag (`pulp` will do for you).

I don't actually see `1.0.1` mentioned anywhere - it's `1.0.0` in package.json - where do you want me to upgrade the version and what do you suggest? (SemVer should be `2.0.0` I guess)

2022-08-17 14:08 UTC, maurges commented
No problem for comments, in fact I might be hypercorrecting here, as English is not my native language as well. I just like it to look neat.

RE version: I don't even remember myself where it goes. But please do change what the package.json says at least, we'll figure out the rest later. You are correct, it should say 2.0

2022-08-17 14:54 UTC, CarstenKoenig commented
Hi,

version in package.json is now at 2.0.0.

As far as I know for bower/purescript-package-set it's mainly done via Tags here. Psc-Package/Dhall will be fine with either commit/branch/tag but if you want to get this (re-)added to the current set it should have a current Tag I think.

2022-08-18 14:04 UTC, d86leader requested changes
Just some more style changes and we're good to go (I forgor to press the "send" button yesterday..)

2022-08-18 14:04 UTC, maurges commented on src/Data/UndefinedOr.purs
> +-- | unlawful version of `map`. Caution does not obey the functor laws
Please capitalize it and put the colon after "Caution"

2022-08-18 16:18 UTC, CarstenKoenig commented on src/Data/UndefinedOr.purs
> +-- | unlawful version of `map`. Caution does not obey the functor laws
Ok - please check it now.

2022-08-19 09:08 UTC, d86leader commented on src/Data/UndefinedOr.purs
> +-- | unlawful version of `map`. Caution does not obey the functor laws
Thanks!

2022-08-19 09:08 UTC, d86leader approved these changes

2022-08-19 09:08 UTC, merged

2022-08-19 09:12 UTC, d86leader commented
Great, now the only thing that's left is release it I guess. By the way, if the release process can be deferred to another person, I hereby grant you, @CarstenKoenig a permission to do a 2.0.0 release of this version of the code currently visible in the "master" branch for package sets, effective strictly between 2022-08-18 and 2022-09-01
=)